### ISSUE TITLE
Cannot work with example

### ISSUE THREAD

**Issue by moonstarsky37** [7rs/line4py#5]
I have install the line4py with virtualenv in python3.9
I clone the repository and pip install all the package need
When I run the ```qrcode.py```, it shows
![圖片](https://github.com/7rs/line4py/assets/9031339/b9f448fc-65d7-4384-9bc0-da7688ddeda1)

**Comment by 7rs** [comment]
This project stopped long ago and probably so LINE developers changed the specifications and that error occurred.
I dunno about the current unofficial LINE libraries but probably CHLINE is newest. CHLINE has been stopped and maybe you gotta do reverse engineering.

Also, don't login with this library because your account may be banned or penalized.

https://github.com/DeachSword/CHRLINE

**Comment by moonstarsky37** [comment]
Thank you for your response. 
I haven't tried this repository yet, but I'll give it a try.
If it is no longer being developed, then I might also close this issue.
